# Generated by Django 5.2.6 on 2025-10-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('off_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customer1',
        ),
    ]
